### ISSUE TITLE
Error while using `$where` with DateTime values

### ISSUE THREAD

**Issue by ibarrae** [tanweerdev/fat_ecto#46]
Hi! First, let me thank you for all the effort in this library :tada: 

I'm opening this issue because there's seems to be an error when applying `eq` operations with `DateTime` values (potentially with other date-time structs too).

The one bellow works correctly:

``` elixir
opts = %{
  "child_table" => %{
    "$where" => %{
      "inserted_at" => %{
        "$gt" => ~U[2020-01-01 00:00:00Z],
        "$lt" => ~U[2022-01-01 00:00:00Z]
      },
      "value" => 3000
    }
  }
}

build!(MyApp.Model, %{"include" => opts})
```

But the following example doesn't seem to work :disappointed:. Is there's something wrong with the options and trying to apply in this case?

``` elixir
opts = %{
  "child_table" => %{
    "$where" => %{
      "inserted_at" => ~U[2022-01-01 00:00:00Z],
      "value" => 3000
    }
  }
}

build!(MyApp.Model, %{"include" => opts})
```

Here's the stack trace of the error:

``` elixir
[error] ** (Protocol.UndefinedError) protocol Enumerable not implemented for ~U[2020-01-01 00:00:00Z] of type DateTime (a struct)
    (elixir 1.11.2) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir 1.11.2) lib/enum.ex:141: Enumerable.reduce/3
    (elixir 1.11.2) lib/enum.ex:3461: Enum.reduce/3
    (stdlib 3.14) maps.erl:233: :maps.fold_1/3
    (fat_ecto 0.5.0) lib/fat_ecto/query/where.ex:741: FatEcto.FatQuery.FatWhere.build_where/4
    (fat_ecto 0.5.0) lib/fat_ecto/query/include.ex:113: anonymous fn/4 in FatEcto.FatQuery.FatInclude.build_include/4
    (stdlib 3.14) maps.erl:233: :maps.fold_1/3
```

**Comment by tanweerdev** [comment]
Hi @ibarrae . Thanks for submitting an issue. if possible, can you please create a small project where you add this failing example. it would be easier for me to debug this way

**Comment by ibarrae** [comment]
For sure @tanweerdev! I created a fork and the failing example is in this [commit](https://github.com/ibarrae/fat_ecto/commit/682935c20b226e5e30b30253619ba17811cec952). In any case, here's the snippet for it under `where_test.exs`

``` elixir
test "failing example for using == for DateTime values" do
    opts = %{
      "$where" => %{
        "start_date" => DateTime.utc_now()
      }
    }

    Query.build!(FatEcto.FatDoctor, opts)
  end
```

**Comment by tanweerdev** [comment]
Thanks @ibarrae checking and I will get back to you

**Comment by tanweerdev** [comment]
@ibarrae please give me push access to your repo. I have a possible fix. Thanks

**Comment by tanweerdev** [comment]
@ibarrae please check the same test case. its fixed and merged
